[package]
name = "json2cstr"
version = "0.1.0"
authors = ["Mathew Harman <mathew.harman@gmail.com>"]
edition = "2018"

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true

[dependencies]
anyhow = "*"
structopt = "*"
